export * from './player.constants'
export * from './weeklyStats.constants'

export const dataFile = "Massive Data File"; 

export const configData = {
  database: {
    host: "localhost",
    port: 5432,
    username: "postgres",
    password: "password",
    database: "statServer"
  },
  nfl: {
    players: {
      columns: {
        career_status: "status",
        game_status_abbr: "status_desription_abbr",
        game_status: "status_short_description",
        esb_id: "esb_id",
        gsis_id: "gsis_id",
        gsis_it_id: "gsis_it_id",
        smart_id: "smart_id",
        first_name: "first_name",
        last_name: "last_name",
        full_name: "display_name",
        short_name: "short_name",
        suffix: "suffix",
        birth_date: "birth_date",
        college_name: "college_name",
        college_conference: "college_conference",
        height: "height",
        weight: "weight",
        headshot_url: "headshot",
        position_group: "position_group",
        position: "position",
        jersey_number: "jersey_number",
        years_of_experience: "years_of_experience",
        team: "team_abbr",
        team_seq: "team_seq",
        team_id: "current_team_id",
        football_name: "",
        entry_year: "",
        rookie_year: "rookie_year",
        draft_team: "draft_club",
        draft_number: "draft_number",
        uniform_number: "",
        draft_round: "draft_round",
        season: "season"
      },
      url: "https://github.com/nflverse/nflverse-data/releases/download/players/players.csv"
    },
    player_weekly_stats: {
      columns: {
        gsis_id: "player_id",
        short_name: "player_name",
        full_name: "player_display_name",
        headshot_url: "headshot",
        position: "position",
        position_group: "position_group",
        team: "team",
        season: "season",
        week: "week",
        game_type: "game_type",
        opponent: "opponent",
        fantasy_points: "fantasy_points",
        fantasy_points_ppr: "fantasy_points_ppr",
        completions: "completions",
        attempts: "attempts",
        pass_yards: "pass_yards",
        pass_tds: "pass_tds",
        interceptions: "interceptions",
        sacks: "sacks",
        sack_yards: "sack_yards",
        sack_fumbles: "sack_fumbles",
        sack_fumbles_lost: "sack_fumbles_lost",
        pass_air_yards:"air_yards",
        pass_yards_after_catch: "yards_after_catch",
        pass_first_downs: "pass_first_downs",
        pass_epa: "pass_epa",
        pass_2pt_conversions: "pass_two_pt_conversions",
        pass_air_conversion_ratio: "pass_air_conversion_ratio",
        dakota: "dakota",
        carries: "carries",
        rush_yards: "rush_yards",
        rush_tds: "rush_tds",
        rush_fumbles: "rush_fumbles",
        rush_fumbles_lost: "rush_fumbles_lost",
        rush_first_downs: "rush_first_downs",
        rush_epa: "rush_epa",
        rush_2pt_conversions: "rush_two_pt_conversions",        
        special_teams_tds: "special_teams_tds",
        receptions: "receptions",
        targets: "targets",
        rec_yards: "rec_yards",
        rec_tds: "rec_tds",
        rec_fumbles: "rec_fumbles",
        rec_fumbles_lost: "rec_fumbles_lost",
        rec_air_yards: "air_yards",
        rec_yards_after_catch: "yards_after_catch",
        rec_first_downs: "rec_first_downs",
        rec_epa: "rec_epa",
        rec_2pt_conversions: "rec_two_pt_conversions",
        rec_air_conversion_ratio: "rec_air_conversion_ratio",
        target_share: "target_share",
        air_yards_share: "air_yards_share",
        weighted_opportunity_rating: "weighted_opportunity_rating",
      },
      "url": "https://github.com/nflverse/nflverse-data/releases/download/player_stats/player_stats_2023.csv"
    }
  }
};