import type { 
    RawWeeklyStatDefData, 
    DefData as WeeklyDefData,
  } from '../../../../src/interfaces/nfl/nflWeeklyStatsDef';

export const weeklyStatDefRecord = {
    player_id: 1001,
    player_weekly_id: 100,
    gsis_id: 'string',
    full_name: 'string',
    short_name: 'string',
    headshot_url: 'string',
    position: 'string',
    position_group: 'string',
    team: 'string',
    season: 'string',
    week: 2,
    tackles: 1,
    tackles_solo: 0,
    tackle_with_assists: 1,
    tackle_assists: 1,
    tackles_for_loss: 1,
    tackles_for_loss_yards: 3,
    fumbles_forced: 0,
    sacks: 1,
    sack_yards: 3,
    qb_hits: 2,
    interceptions: 0,
    interception_yards: 0,
    pass_defended: 1,
    tds: 0,
    fumbles: 0,
    fumble_recovery_own: 0,
    fumble_recovery_yards_own: 0,
    fumble_recovery_opp: 0,
    fumble_recovery_yards_opp: 0,
    safety: 1,
    penalty: 2,
    penalty_yards: 10,
  };

  export const noRawWeeklyStatDefData: RawWeeklyStatDefData[] = [];
  export const rawWeeklyStatDefData: RawWeeklyStatDefData[] = [weeklyStatDefRecord];
  
  export const defData: WeeklyDefData = {
    player_weekly_id: weeklyStatDefRecord.player_weekly_id,
    tackles: weeklyStatDefRecord.tackles,
    tackles_solo: weeklyStatDefRecord.tackles_solo,
    tackle_with_assists: weeklyStatDefRecord.tackle_with_assists,
    tackle_assists: weeklyStatDefRecord.tackle_assists,
    tackles_for_loss: weeklyStatDefRecord.tackles_for_loss,
    tackles_for_loss_yards: weeklyStatDefRecord.tackles_for_loss_yards,
    fumbles_forced: weeklyStatDefRecord.fumbles_forced,
    sacks: weeklyStatDefRecord.sacks,
    sack_yards: weeklyStatDefRecord.sack_yards,
    qb_hits: weeklyStatDefRecord.qb_hits,
    interceptions: weeklyStatDefRecord.interceptions,
    interception_yards: weeklyStatDefRecord.interception_yards,
    pass_defended: weeklyStatDefRecord.pass_defended,
    tds: weeklyStatDefRecord.tds,
    fumbles: weeklyStatDefRecord.fumbles,
    fumble_recovery_own: weeklyStatDefRecord.fumble_recovery_own,
    fumble_recovery_yards_own: weeklyStatDefRecord.fumble_recovery_yards_own,
    fumble_recovery_opp: weeklyStatDefRecord.fumble_recovery_opp,
    fumble_recovery_yards_opp: weeklyStatDefRecord.fumble_recovery_yards_opp,
    safety: weeklyStatDefRecord.safety,
    penalty: weeklyStatDefRecord.penalty,
    penalty_yards: weeklyStatDefRecord.penalty_yards,
  };