export interface NFLWeeklyNextGenStatsPass {
    columns: {
      season: string,
      week: string,
      game_type: string,
      position: string,
      jersey_number: string,
      team: string,
      first_name: string;
      full_name: string,
      last_name: string,
      short_name: string,
      gsis_id: string,
      aggressiveness: string,
      avg_time_to_throw: string,
      avg_air_distance: string,
      max_air_distance: string,
      avg_completed_air_yards: string,
      avg_intended_air_yards: string,
      avg_air_yards_differential: string,
      avg_air_yards_to_sticks: string,
      max_completed_air_distance: string,
      passer_rating: string,
      completion_pct: string,
      expected_completion_pct: string,
      completions_above_expectation_pct: string,
    },
    urls: string[],
}

export interface NFLWeeklyNextGenStatsRush {
    columns: {
      season: string,
      week: string,
      game_type: string,
      position: string,
      jersey_number: string,
      team: string,
      first_name: string;
      full_name: string,
      last_name: string,
      short_name: string,
      gsis_id: string,
      efficiency: string,
      attempts_gte_eight_defenders_pct: string,
      avg_time_to_los: string,
      expected_yards: string,
      yards_over_expected: string,
      avg_yards: string,
      yards_over_expected_per_att: string,
      yards_over_expected_pct: string,
    },
    urls: string[],
}

export interface NFLWeeklyNextGenStatsRec {
    columns: {
      season: string,
      week: string,
      game_type: string,
      position: string,
      jersey_number: string,
      team: string,
      first_name: string;
      full_name: string,
      last_name: string,
      short_name: string,
      gsis_id: string,
      avg_cushion: string,
      avg_separation: string,
      avg_intended_air_yards: string,
      catch_pct: string,
      share_of_intended_air_yards_pct: string,
      avg_yac: string,
      avg_expected_yac: string,
      avg_yac_above_expectation: string,
    },
    urls: string[],
}