export interface Config {
    nfl: {
        players: {
          columns: {
            // player table
            career_status: string,
            game_status_abbr: string,
            game_status: string,
            esb_id: string,
            gsis_id: string,
            gsis_it_id: string,
            smart_id: string,
            first_name: string,
            last_name: string,
            full_name: string,
            short_name: string,
            suffix: string,
            // player bio table
            birth_date: string,
            college_name: string,
            college_conference: string,
            height: string,
            weight: string,
            headshot_url: string,
            // player league table
            position_group: string,
            position: string,
            jersey_number: string,
            years_of_experience: string,
            team: string,
            team_seq: string,
            team_id: string,
            football_name: string,
            entry_year: string,
            rookie_year: string,
            draft_team: string,
            draft_number: string,
            uniform_number: string,
            draft_round: string,
            season: string,
          },
          urls: string[],
        },
        player_weekly_stats: {
          columns: {
            // player table
            gsis_id: string,
            short_name: string,
            full_name: string,
            // bio table
            headshot_url: string,
            // league table
            position: string,
            position_group: string,
            team: string,
            // player weekly stat table
            season: string,
            week: string,
            game_type: string,
            opponent: string,
            fantasy_points: string,
            fantasy_points_ppr: string,
            // player weekly stat pass table
            completions: string,
            attempts: string,
            pass_yards: string,
            pass_tds: string,
            interceptions: string,
            sacks: string,
            sack_yards: string,
            sack_fumbles: string,
            sack_fumbles_lost: string,
            pass_air_yards: string,
            pass_yards_after_catch: string,
            pass_first_downs: string,
            pass_epa: string,
            pass_2pt_conversions: string,
            pass_air_conversion_ratio: string,
            dakota: string,
            // player weekly stat rush table
            carries: string,
            rush_yards: string,
            rush_tds: string,
            rush_fumbles: string,
            rush_fumbles_lost: string,
            rush_first_downs: string,
            rush_epa: string,
            rush_2pt_conversions: string,
            special_teams_tds: string,
            // player weekly stat pass table
            receptions: string,
            targets: string,
            rec_yards: string,
            rec_tds: string,
            rec_fumbles: string,
            rec_fumbles_lost: string,
            rec_air_yards: string,
            rec_yards_after_catch: string,
            rec_first_downs: string,
            rec_epa: string,
            rec_2pt_conversions: string,
            rec_air_conversion_ratio: string,
            target_share: string,
            air_yards_share: string,
            weighted_opportunity_rating: string,
          },
          urls: string[],
        },
        player_weekly_def_stats: {
          columns: {
            // player table
            gsis_id: string,
            short_name: string,
            full_name: string,
            // bio table
            headshot_url: string,
            // league table
            position: string,
            position_group: string,
            team: string,
            // player weekly stat table
            season: string,
            week: string,
            // player weekly def stat table
            tackles: string,
            tackles_solo: string,
            tackle_with_assists: string,
            tackle_assists: string,
            tackles_for_loss: string,
            tackles_for_loss_yards: string,
            fumbles_forced: string,
            sacks: string,
            sack_yards: string,
            qb_hits: string,
            interceptions: string,
            interception_yards: string,
            pass_defended: string,
            tds: string,
            fumbles: string,
            fumble_recovery_own: string,
            fumble_recovery_yards_own: string,
            fumble_recovery_opp: string,
            fumble_recovery_yards_opp: string,
            safety: string,
            penalty: string,
            penalty_yards: string,
          },
          urls: string[],
        },
        player_weekly_kick_stats: {
          columns: {
            // player table
            gsis_id: string,
            short_name: string,
            // league table
            team: string,
            // player weekly stat table
            season: string,
            week: string,
            game_type: string,
            // player weekly kick stat table
            fg_made: string,
            fg_missed: string,
            fg_blocked: string,
            fg_long: string,
            fg_att: string,
            fg_pct: string,
            pat_made: string,
            pat_missed: string,
            pat_blocked: string,
            pat_att: string,
            pat_pct: string,
            fg_made_distance: string,
            fg_missed_distance: string,
            fg_blocked_distance: string,
            gwfg_att: string,
            gwfg_distance: string,
            gwfg_made: string,
            gwfg_missed: string,
            gwfg_blocked: string,
            fg_made_0_19: string,
            fg_made_20_29: string,
            fg_made_30_39: string,
            fg_made_40_49: string,
            fg_made_50_59: string,
            fg_made_60_: string,
            fg_missed_0_19: string,
            fg_missed_20_29: string,
            fg_missed_30_39: string,
            fg_missed_40_49: string,
            fg_missed_50_59: string,
            fg_missed_60_: string,
            fg_made_list: string,
            fg_missed_list: string,
            fg_blocked_list: string,
          },
          urls: string[],
        },
    },
    database: {
      username: string,
      host: string,
      database: string,
      password: string,
      port: number,
    }
  }