export interface Config {
    nfl: {
        players: {
          columns: {
            // player table
            career_status: string,
            game_status_abbr: string,
            game_status: string,
            esb_id: string,
            gsis_id: string,
            gsis_it_id: string,
            smart_id: string,
            first_name: string,
            last_name: string,
            full_name: string,
            short_name: string,
            suffix: string,
            // player bio table
            birth_date: string,
            college_name: string,
            college_conference: string,
            height: string,
            weight: string,
            headshot_url: string,
            // player league table
            position_group: string,
            position: string,
            jersey_number: string,
            years_of_experience: string,
            team: string,
            team_seq: string,
            team_id: string,
            football_name: string,
            entry_year: string,
            rookie_year: string,
            draft_team: string,
            draft_number: string,
            uniform_number: string,
            draft_round: string,
            season: string,
          },
          url: string,
        },
        player_weekly_stats: {
          columns: {
            // player table
            player_id: string,
            player_name: string,
            player_display_name: string,
            position: string,
            position_group: string,
            headshot_url: string,
            recent_team: string,
            // player weekly stat table
            season: string,
            week: string,
            season_type: string,
            opponent_team: string,
            fantasy_points: string,
            fantasy_points_ppr: string,
            // player weekly stat pass table
            completions: string,
            attempts: string,
            passing_yards: string,
            passing_tds: string,
            interceptions: string,
            sacks: string,
            sack_yards: string,
            sack_fumbles: string,
            sack_fumbles_lost: string,
            passing_air_yards: string,
            passing_yards_after_catch: string,
            passing_first_downs: string,
            passing_epa: string,
            passing_2pt_conversions: string,
            pacr: string,
            dakota: string,
            // player weekly stat rush table
            carries: string,
            rushing_yards: string,
            rushing_tds: string,
            rushing_fumbles: string,
            rushing_fumbles_lost: string,
            rushing_first_downs: string,
            rushing_epa: string,
            rushing_2pt_conversions: string,
            special_teams_tds: string,
            // player weekly stat pass table
            receptions: string,
            targets: string,
            receiving_yards: string,
            receiving_tds: string,
            receiving_fumbles: string,
            receiving_fumbles_lost: string,
            receiving_air_yards: string,
            receiving_yards_after_catch: string,
            receiving_first_downs: string,
            receiving_epa: string,
            receiving_2pt_conversions: string,
            racr: string,
            target_share: string,
            air_yards_share: string,
            wopr: string,
          },
          url: string,
        },
    },
    database: {
      username: string,
      host: string,
      database: string,
      password: string,
      port: number,
    }
  }