import type { 
  RawSeasonAdvStatRecData, 
  SeasonAdvStatRecData,
} from '@interfaces/nfl/seasonAdvStats/seasonAdvStatsRec';

export const seasonAdvStatRecRecord = {
  player_id: 1001,
  player_season_id: 100,
  full_name: 'string',
  short_name: 'string',
  season: "2003",
  team: "KC",
  pfr_id: "ABC",
  age: 23,
  games_played: 16,
  games_started: 14,
  targets: 345,
  receptions: 112,
  yards: 1605,
  tds: 11,
  longest_rec: 67,
  air_yards: 1375,
  air_yards_avg: 18.2,
  yards_after_contact: 230,
  yards_after_contact_avg: 8.8,
  adot: 18.2,
  broken_tackles: 22,
  broken_tackles_avg: 28,
  drops: 9,
  drop_pct: 0.05,
  interceptions: 4,
  qb_rating: 98.6,
};

export const noRawSeasonStatRecData: RawSeasonAdvStatRecData[] = [];
export const rawSeasonStatRecData: RawSeasonAdvStatRecData[] = [seasonAdvStatRecRecord];

export const seasonAdvRecData: SeasonAdvStatRecData = {
  player_season_id: seasonAdvStatRecRecord.player_season_id,
  targets: seasonAdvStatRecRecord.targets,
  receptions: seasonAdvStatRecRecord.receptions,
  yards: seasonAdvStatRecRecord.yards,
  tds: seasonAdvStatRecRecord.tds,
  longest_rec: seasonAdvStatRecRecord.longest_rec,
  air_yards: seasonAdvStatRecRecord.air_yards,
  air_yards_avg: seasonAdvStatRecRecord.air_yards_avg,
  yards_after_contact: seasonAdvStatRecRecord.yards_after_contact,
  yards_after_contact_avg: seasonAdvStatRecRecord.yards_after_contact_avg,
  adot: seasonAdvStatRecRecord.adot,
  broken_tackles: seasonAdvStatRecRecord.broken_tackles,
  broken_tackles_avg: seasonAdvStatRecRecord.broken_tackles_avg,
  drops: seasonAdvStatRecRecord.drops,
  drop_pct: seasonAdvStatRecRecord.drop_pct,
  interceptions: seasonAdvStatRecRecord.interceptions,
  qb_rating: seasonAdvStatRecRecord.qb_rating,
};
  
export const seasonAdvStatsRecColumns = {
    "season": "season",
    "full_name": "player",
    "pfr_id": "pfr_id",
    "team": "team",
    "age": "age",
    "position": "position",
    "games_played": "g",
    "games_started": "gs",
    "targets": "tgt",
    "receptions": "rec",
    "yards": "yds",
    "tds": "td",
    "longest_rec": "x1d",
    "air_yards": "ybc",
    "air_yards_avg": "ybc_r",
    "yards_after_contact": "yac",
    "yards_after_contact_avg": "yac_r",
    "adot": "adot",
    "broken_tackles": "brk_tkl",
    "broken_tackles_avg": "rec_br",
    "drops": "drop",
    "drop_pct": "drop_percent",
    "interceptions": "int",
    "qb_rating": "rat",
    "loaded": ""
};