import type { 
  RawSeasonAdvStatDefData, 
  SeasonAdvStatDefData,
} from '../../../../../src/interfaces/nfl/seasonAdvStats/seasonAdvStatsDef';
  
export const seasonAdvStatDefRecord = {
  player_id: 1001,
  player_season_id: 100,
  full_name: 'string',
  short_name: 'string',
  season: "2003",
  team: "KC",
  pfr_id: "ABC",
  age: 23,
  games_played: 16,
  games_started: 14,
  interceptions: 4,
  targets: 421,
  completions_allowed: 86,
  completion_pct: 0.38,
  yards_allowed: 795,
  yards_allowed_per_cmp: 12.7,
  yards_allowed_per_tgt: 4.2,
  tds_allowed: 3,
  passer_rating_allowed: 68.2,
  adot: 12.2,
  air_yards_completed: 625,
  yards_after_catch: 170,
  blitzed: 88,
  hurried: 12,
  qbkd: 6,
  sacks: 3,
  pressures: 12,
  tackles_combined: 288,
  tackles_missed: 21,
  tackles_missed_pct: 0.12,
};
  
export const noRawSeasonStatDefData: RawSeasonAdvStatDefData[] = [];
export const rawSeasonStatDefData: RawSeasonAdvStatDefData[] = [seasonAdvStatDefRecord];

export const seasonAdvDefData: SeasonAdvStatDefData = {
  player_season_id: seasonAdvStatDefRecord.player_season_id,
  interceptions: seasonAdvStatDefRecord.interceptions,
  targets: seasonAdvStatDefRecord.targets,
  completions_allowed: seasonAdvStatDefRecord.completions_allowed,
  completion_pct: seasonAdvStatDefRecord.completion_pct,
  yards_allowed: seasonAdvStatDefRecord.yards_allowed,
  yards_allowed_per_cmp: seasonAdvStatDefRecord.yards_allowed_per_cmp,
  yards_allowed_per_tgt: seasonAdvStatDefRecord.yards_allowed_per_tgt,
  tds_allowed: seasonAdvStatDefRecord.tds_allowed,
  passer_rating_allowed: seasonAdvStatDefRecord.passer_rating_allowed,
  adot: seasonAdvStatDefRecord.adot,
  air_yards_completed: seasonAdvStatDefRecord.air_yards_completed,
  yards_after_catch: seasonAdvStatDefRecord.yards_after_catch,
  blitzed: seasonAdvStatDefRecord.blitzed,
  hurried: seasonAdvStatDefRecord.hurried,
  qbkd: seasonAdvStatDefRecord.qbkd,
  sacks: seasonAdvStatDefRecord.sacks,
  pressures: seasonAdvStatDefRecord.pressures,
  tackles_combined: seasonAdvStatDefRecord.tackles_combined,
  tackles_missed: seasonAdvStatDefRecord.tackles_missed,
  tackles_missed_pct: seasonAdvStatDefRecord.tackles_missed_pct,
};
  
export const seasonAdvStatsDefColumns = {
  "season": "season",
  "full_name": "player",
  "pfr_id": "pfr_id",
  "team": "team",
  "age": "age",
  "position": "position",
  "games_played": "g",
  "games_started": "gs",
  "interceptions": "int",
  "targets": "tgt",
  "completions_allowed": "cmp",
  "completion_pct": "cmp_percent",
  "yards_allowed": "yds",
  "yards_allowed_per_cmp": "yds_cmp",
  "yards_allowed_per_tgt": "yds_tgt",
  "tds_allowed": "td",
  "passer_rating_allowed": "rat",
  "adot": "dadot",
  "air_yards_completed": "air",
  "yards_after_catch": "yac",
  "blitzed": "bltz",
  "hurried": "hrry",
  "qbkd": "qbkd",
  "sacks": "sk",
  "pressures": "prss",
  "tackles_combined": "comb",
  "tackles_missed": "m_tkl",
  "tackles_missed_pct": "m_tkl_percent",
  "loaded": ""
};