import type { 
  RawSeasonAdvStatPassData, 
  SeasonAdvStatPassData,
} from '../../../../../src/interfaces/nfl/seasonAdvStats/seasonAdvStatsPass';

export const seasonAdvStatPassRecord = {
  player_id: 1001,
  player_season_id: 100,
  full_name: 'string',
  short_name: 'string',
  season: "2003",
  team: "KC",
  pfr_id: "ABC",
  age: 23,
  games_played: 16,
  games_started: 14,
  attempts: 2500,
  throw_aways: 75,
  spikes: 22,
  drops: 55,
  drop_pct: .12,
  bad_throws: 88,
  bad_throw_pct: .24,
  pocket_time: 2.45,
  blitzed: 564,
  hurried: 784,
  hit: 220,
  pressured: 900,
  pressured_pct: .45,
  batted_balls: 77,
  on_tgt_throws: 2100,
  on_tgt_throws_pct: 0.89,
  rpo_plays: 2250,
  rpo_yards: 1274,
  rpo_pass_attempts: 1750,
  rpo_pass_yards: 859,
  rpo_rush_attempts: 500,
  rpo_rush_yards: 425,
  pa_pass_attempts: 0,
  pa_pass_yards: 0,
};

export const noRawSeasonStatPassData: RawSeasonAdvStatPassData[] = [];
export const rawSeasonStatPassData: RawSeasonAdvStatPassData[] = [seasonAdvStatPassRecord];

export const seasonAdvPassData: SeasonAdvStatPassData = {
  player_season_id: seasonAdvStatPassRecord.player_season_id,
  attempts: seasonAdvStatPassRecord.attempts,
  throw_aways: seasonAdvStatPassRecord.throw_aways,
  spikes: seasonAdvStatPassRecord.spikes,
  drops: seasonAdvStatPassRecord.drops,
  drop_pct: seasonAdvStatPassRecord.drop_pct,
  bad_throws: seasonAdvStatPassRecord.bad_throws,
  bad_throw_pct: seasonAdvStatPassRecord.bad_throw_pct,
  pocket_time: seasonAdvStatPassRecord.pocket_time,
  blitzed: seasonAdvStatPassRecord.blitzed,
  hurried: seasonAdvStatPassRecord.hurried,
  hit: seasonAdvStatPassRecord.hit,
  pressured: seasonAdvStatPassRecord.pressured,
  pressured_pct: seasonAdvStatPassRecord.pressured_pct,
  batted_balls: seasonAdvStatPassRecord.batted_balls,
  on_tgt_throws: seasonAdvStatPassRecord.on_tgt_throws,
  on_tgt_throws_pct: seasonAdvStatPassRecord.on_tgt_throws_pct,
  rpo_plays: seasonAdvStatPassRecord.rpo_plays,
  rpo_yards: seasonAdvStatPassRecord.rpo_yards,
  rpo_pass_attempts: seasonAdvStatPassRecord.rpo_pass_attempts,
  rpo_pass_yards: seasonAdvStatPassRecord.rpo_pass_yards,
  rpo_rush_attempts: seasonAdvStatPassRecord.rpo_rush_attempts,
  rpo_rush_yards: seasonAdvStatPassRecord.rpo_rush_yards,
  pa_pass_attempts: seasonAdvStatPassRecord.pa_pass_attempts,
  pa_pass_yards: seasonAdvStatPassRecord.pa_pass_yards,
};

export const seasonAdvStatsPassColumns = {
  "full_name": "player",
  "team": "team",
  "attempts": "pass_attempts",
  "throw_aways": "throwaways",
  "spikes": "spikes",
  "drops": "drops",
  "drop_pct": "drop_pct",
  "bad_throws": "bad_throws",
  "bad_throw_pct": "bad_throw_pct",
  "season": "season",
  "pfr_id": "pfr_id",
  "pocket_time": "pocket_time",
  "blitzed": "times_blitzed",
  "hurried": "times_hurried",
  "hit": "times_hit",
  "pressured": "times_pressured",
  "pressured_pct": "pressure_pct",
  "batted_balls": "batted_balls",
  "on_tgt_throws": "on_tgt_throws",
  "on_tgt_throws_pct": "on_tgt_pct",
  "rpo_plays": "rpo_plays",
  "rpo_yards": "rpo_yards",
  "rpo_pass_attempts": "rpo_pass_att",
  "rpo_pass_yards": "rpo_pass_yards",
  "rpo_rush_attempts": "rpo_rush_att",
  "rpo_rush_yards": "rpo_rush_yards",
  "pa_pass_attempts": "pa_pass_att",
  "pa_pass_yards": "pa_pass_yards",
};